title: Fast Data Transfer
description: FDT is an open source application for efficient data transfers capable of reading and writing at disk speed over wide area networks (with standard TCP)
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
gems:
  - jekyll-menus
